[project]
name = "xun-agent"
version = "1.1.1"
description = "An autonomous mini LLM agent with tooling."
readme = "README.md"
keywords = ["agent", "llm", "llm-agent"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
]
authors = [
    { name = "limengxun", email = "limengxun45@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.0",
    "docker>=7.1.0",
    "html-to-markdown>=3.12.2",
    "jinja2>=3.1.6",
    "json-repair>=0.63.4",
    "markdown>=3.10.3",
    "openai>=3.8.0",
    "pillow>=12.3.0",
    "playwright>=1.62.0",
    "puremagic>=2.2.0",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "rich>=15.0.0",
    "typing-extensions>=4.16.0",
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
xun = "xun:main"
xuns = "xun:main_serve"
xunc = "xun:main_container"
xunx = "xun.supervisor:main"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "src"
module-name = "xun"
